# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-atsuya-extension-only-app"
client_id = "17ed4d9fbd76a96b461fbad3688b8af6"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "test-atsuya-dev-store.myshopify.com"
